//! Identity — self-reflexive agent registration.
//!
//! Identity is NOT a special-case structure. It is an entry in the `identity`
//! volume of the *global* capsule, addressed by `name:<agent>` (the name is the
//! identity's natural address — a numeric id would carry no meaning).
//!
//! Two layers, kept distinct:
//!
//!   - **identity** — `name:edelweiss`. Permanent, unique, the answer to "who
//!     is this." Lives as one entry in `identity` volume. Selecting it loads the
//!     agent's meta (recall bootstrap).
//!   - **instance** — `name:edelweiss#<hash>`. Born each time the identity is
//!     loaded into a running context (a session). Distinguishes concurrent
//!     copies of the same identity (two windows, CLI + MCP). The hash is random,
//!     minted on load, lives in session state — not persisted in the identity
//!     entry.
//!
//! `select_identity` is therefore both identity confirmation AND recall
//! bootstrap: it resolves the identity, mints an instance, and returns the
//! identity's meta. Permissions are out of scope (v1: full access; identity's
//! job is recall, not gating).

use anyhow::{anyhow, Result};

use crate::model::{Edge, MemRef};
use crate::storage::{AutomergeStorage, Storage};

/// The volume holding agent identities in the global capsule.
pub const IDENTITY_VOLUME: &str = "identity";

/// A resolved agent: the permanent identity plus the ephemeral instance.
#[derive(Debug, Clone)]
pub struct ResolvedIdentity {
    /// `name:edelweiss` — permanent identity.
    pub identity: String,
    /// `name:edelweiss#9f2a` — this session's instance marker.
    pub instance: String,
    /// The instance hash alone (`9f2a`).
    pub instance_hash: String,
    /// Human-readable display name (from the identity entry's first heading).
    pub display: String,
    /// The identity entry's content (its meta / "who I am").
    pub meta: String,
}

/// Select an identity by name, minting a fresh instance.
///
/// Finds the identity entry by its `name:<name>` tag in the global capsule's
/// `identity` volume (the id is a sequential `identity:01`, not name-based —
/// the name is a tag, keeping the write API uniform across all volumes). If the
/// identity doesn't exist, returns an error — register it first.
///
/// This is the recall-bootstrap step: the returned meta is what the agent
/// operates on.
pub fn select_identity(
    global: &AutomergeStorage,
    name: &str,
) -> Result<ResolvedIdentity> {
    let name_tag = format!("name:{}", name);
    let mut found = global.find_by_tag(IDENTITY_VOLUME, &[name_tag.clone()])?;
    let entry = found
        .pop()
        .ok_or_else(|| anyhow!("identity '{}' not registered. Register it first.", name_tag))?;

    let instance_hash = mint_instance_hash();
    Ok(ResolvedIdentity {
        identity: name_tag.clone(),
        instance: format!("{}#{}", name_tag, instance_hash),
        instance_hash,
        display: extract_display(&entry.content, name),
        meta: entry.content,
    })
}

/// Register a new identity in the global capsule.
///
/// Writes an entry in the `identity` volume with a `name:<name>` tag. The id is
/// sequential (`identity:01`) — generated by storage, not name-based — keeping
/// the write API uniform. The name lives as a tag, which is how identities are
/// looked up (select_identity searches by tag).
pub fn register_identity(
    global: &mut AutomergeStorage,
    name: &str,
    display: &str,
    description: &str,
    author: &str,
) -> Result<(String, String)> {
    let content = format!("## {}\n\n{}", display, description);
    let tags = vec![format!("name:{}", name), "type:identity".to_string()];
    global.write(
        IDENTITY_VOLUME,
        None, // new entry — storage generates the sequential id
        &content,
        &tags,
        &[],
        author,
        &format!("register identity name:{}", name),
        &[],
        &[],
    )
}

/// List all registered identity names (extracted from the `name:` tag).
pub fn list_identities(global: &AutomergeStorage) -> Result<Vec<String>> {
    let entries = global.find_by_tag(IDENTITY_VOLUME, &["type:identity".to_string()])?;
    let mut names = Vec::new();
    for e in entries {
        for t in &e.tags {
            if let Some(name) = t.strip_prefix("name:") {
                names.push(name.to_string());
            }
        }
    }
    Ok(names)
}

/// The full author string for version writes: identity + instance.
///
/// Every write from a resolved identity records this as its author, so lineage
/// can answer both "whose knowledge is this" (identity) and "which run wrote
/// it" (instance).
pub fn author_for(identity: &ResolvedIdentity) -> String {
    identity.instance.clone()
}

// ─── helpers ───────────────────────────────────────────────────────────────

/// Mint a random instance hash (4 hex chars). Distinguishes concurrent
/// sessions of the same identity — not cryptographically meaningful.
fn mint_instance_hash() -> String {
    // Use a simple time + counter-ish source; instance hashes only need
    // uniqueness within a concurrent set, not unpredictability.
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    // XOR-fold into 16 bits for a 4-hex-char id.
    let folded = (nanos ^ (nanos >> 16) ^ (nanos >> 24)) & 0xFFFF;
    format!("{:04x}", folded)
}

/// Extract a display name from content's first `## ` heading, falling back to
/// the raw name.
fn extract_display(content: &str, fallback: &str) -> String {
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("## ") {
            return rest.trim().to_string();
        }
    }
    fallback.to_string()
}

// Keep these imports used (Edge/MemRef referenced by the write signature path).
#[allow(dead_code)]
fn _type_check(_e: Edge, _m: MemRef) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_then_select_loads_meta() {
        let mut global = AutomergeStorage::new();
        let (id, _hash) = register_identity(
            &mut global,
            "edelweiss",
            "Edelweiss",
            "Primary engine agent. Handles Rust implementation + orchestration.",
            "bootstrap",
        )
        .unwrap();
        assert!(id.starts_with("1") || id == "1", "sequential id, got {}", id);

        let resolved = select_identity(&global, "edelweiss").unwrap();
        assert_eq!(resolved.identity, "name:edelweiss");
        assert_eq!(resolved.display, "Edelweiss");
        assert!(resolved.instance.starts_with("name:edelweiss#"));
        assert!(resolved.meta.contains("Primary engine agent"));
        assert_eq!(resolved.instance_hash.len(), 4);
    }

    #[test]
    fn two_concurrent_loads_mint_different_instances() {
        let mut global = AutomergeStorage::new();
        register_identity(&mut global, "art", "Art", "Visual asset agent.", "bootstrap").unwrap();

        let a = select_identity(&global, "art").unwrap();
        std::thread::sleep(std::time::Duration::from_micros(1100));
        let b = select_identity(&global, "art").unwrap();

        assert_eq!(a.identity, b.identity);
        assert_ne!(a.instance_hash, b.instance_hash, "concurrent loads must differ");
    }

    #[test]
    fn select_unknown_identity_errors() {
        let global = AutomergeStorage::new();
        assert!(select_identity(&global, "nobody").is_err());
    }

    #[test]
    fn identities_listed_by_name() {
        let mut global = AutomergeStorage::new();
        register_identity(&mut global, "edelweiss", "Edelweiss", "x", "b").unwrap();
        register_identity(&mut global, "art", "Art", "y", "b").unwrap();
        let names = list_identities(&global).unwrap();
        assert!(names.contains(&"edelweiss".to_string()));
        assert!(names.contains(&"art".to_string()));
    }
}
