//! Storage trait + Automerge implementation — the meaning-plane substrate.
//!
//! The trait's primitives are operation-shaped, not entry-shaped, per the
//! evolution-graph design (`evolution-graph-memory-history.md`):
//!
//!   - [`Storage::write`] — the only mutation. Every call produces a new
//!     content-addressed [`Version`] and an auto `Parent` edge carrying the
//!     required `intent`. Optionally declares typed edges. The **id is generated
//!     by storage** per the volume's [`IdStrategy`] — the caller never picks it.
//!   - [`Storage::materialize`] — read the latest non-superseded version of an
//!     id as an [`Entry`] (the state-as-entry view).
//!   - [`Storage::lineage`] — the version + intent stream for one id (vertical).
//!   - [`Storage::edges_from`] / [`edges_to`] — typed-edge traversal (horizontal).
//!   - [`Storage::find_by_tag`] — minimal tag lookup (identity, volume meta).
//!
//! Volume behavior (id strategy, supersede policy) is engine-enforced via
//! [`VolumeDef`], stored as capsule metadata — NOT an entry. Supersede-forbidden
//! volumes reject supersede edges at write time.
//!
//! Document shape (one Automerge doc per project):
//! ```text
//! root
//! ├── versions    # map: hash -> Version
//! ├── volumes     # map: volume -> id -> [hashes]   (append order = timeline)
//! ├── volumedefs  # map: volume -> VolumeDef         (id strategy + supersede)
//! └── edges       # list of Edge                     (parent + typed)
//! ```

use std::collections::HashMap;

use anyhow::{anyhow, bail, Result};
use automerge::{AutoCommit, ObjType, ReadDoc, Value, transaction::Transactable};

use crate::model::{Edge, EdgeKind, Entry, IdStrategy, MemRef, SupersedePolicy, Version, VolumeDef};

/// The version graph storage. Implementations own correctness of the
/// content-addressing, parent-edge auto-linking, id generation, and supersede
/// policy enforcement.
pub trait Storage {
    /// Append a new version of an entry, returning `(id, hash)`.
    ///
    /// The **id is generated by storage** per the volume's `IdStrategy` — the
    /// caller does not pass it. For a new entry the next sequential ordinal (or
    /// a random hash) is minted; for a revision of an existing entry, pass
    /// `Some(existing_id)` as `target_id`.
    ///
    /// `intent` is required (the vertical "why"). `typed_edges` optionally
    /// declares horizontal relations; a supersede edge is **rejected** if the
    /// target's volume forbids supersede.
    fn write(
        &mut self,
        volume: &str,
        target_id: Option<&str>,
        content: &str,
        tags: &[String],
        keywords: &[String],
        author: &str,
        intent: &str,
        refs: &[MemRef],
        typed_edges: &[Edge],
    ) -> Result<(String, String)>;

    /// Declare or update a volume's behavioral definition. Idempotent.
    fn declare_volume(&mut self, volume: &str, def: &VolumeDef) -> Result<()>;

    /// Read a volume's definition (defaults if undeclared).
    fn volume_def(&self, volume: &str) -> Result<VolumeDef>;

    /// Read the latest non-superseded version of `volume:id` as an Entry view.
    fn materialize(&self, volume: &str, id: &str) -> Result<Option<Entry>>;

    /// The vertical timeline of one id: versions newest-first with each
    /// version's parent-edge intent. Empty if the id has no versions.
    fn lineage(&self, volume: &str, id: &str) -> Result<Vec<LineageStep>>;

    /// Typed edges originating from a version hash (horizontal, outgoing).
    fn edges_from(&self, hash: &str) -> Result<Vec<Edge>>;

    /// Typed edges pointing at a version hash (horizontal, incoming).
    fn edges_to(&self, hash: &str) -> Result<Vec<Edge>>;

    /// Enumerate all entry ids in a volume.
    fn list(&self, volume: &str) -> Result<Vec<String>>;

    /// Find entries in a volume matching ALL of the given tags. Minimal tag
    /// lookup (used by identity resolution and volume-meta queries; telescope
    /// adds full semantic search later).
    fn find_by_tag(&self, volume: &str, tags: &[String]) -> Result<Vec<Entry>>;

    /// List all volume names present in the capsule.
    fn volume_names(&self) -> Result<Vec<String>>;

    /// Save the document to bytes (for git transport).
    fn save(&mut self) -> Result<Vec<u8>>;
}

/// One step in an entry's evolution timeline.
#[derive(Debug, Clone)]
pub struct LineageStep {
    pub version: Version,
    /// The intent from this version's parent edge (why it was written). Empty
    /// for the root version (no parent).
    pub intent: String,
}

// ─── Automerge implementation ──────────────────────────────────────────────

/// Automerge-backed version-graph storage.
pub struct AutomergeStorage {
    doc: AutoCommit,
}

impl AutomergeStorage {
    /// Create an empty capsule.
    pub fn new() -> Self {
        let mut doc = AutoCommit::new();
        let _ = doc.put_object(automerge::ROOT, "versions", ObjType::Map);
        let _ = doc.put_object(automerge::ROOT, "volumes", ObjType::Map);
        let _ = doc.put_object(automerge::ROOT, "volumedefs", ObjType::Map);
        let _ = doc.put_object(automerge::ROOT, "edges", ObjType::List);
        Self { doc }
    }

    /// Load a capsule from bytes.
    pub fn load(bytes: &[u8]) -> Result<Self> {
        Ok(Self { doc: AutoCommit::load(bytes)? })
    }

    /// The latest non-superseded hash for an id, or None if absent.
    fn latest_hash(&self, volume: &str, id: &str) -> Result<Option<String>> {
        let Some((_, vol_map)) = self.get_volumes() else { return Ok(None) };
        let Some((_, id_list)) = self.doc.get(&vol_map, volume)? else { return Ok(None) };
        let Some((_, hashes_obj)) = self.doc.get(&id_list, id)? else { return Ok(None) };
        // hashes stored as a list; newest last. Walk back for non-superseded.
        let len = self.doc.length(&hashes_obj);
        for i in (0..len).rev() {
            if let Some((Value::Scalar(s), _)) = self.doc.get(&hashes_obj, i)? {
                let h = scalar_str(s.as_ref());
                if let Some(v) = self.read_version(&h)? {
                    if !v.superseded {
                        return Ok(Some(h));
                    }
                }
            }
        }
        Ok(None)
    }

    fn get_volumes(&self) -> Option<(automerge::ObjId, automerge::ObjId)> {
        self.doc.get(automerge::ROOT, "volumes").ok()?.map(|(_, id)| (automerge::ROOT, id))
    }

    fn read_version(&self, hash: &str) -> Result<Option<Version>> {
        let Some((_, versions_map)) = self.doc.get(automerge::ROOT, "versions")? else {
            return Ok(None);
        };
        let Some((Value::Object(ObjType::Map), vobj)) = self.doc.get(&versions_map, hash)? else {
            return Ok(None);
        };
        let content = get_str(&self.doc, &vobj, "content")?.unwrap_or_default();
        let tags = get_list_strings(&self.doc, &vobj, "tags")?;
        let keywords = get_list_strings(&self.doc, &vobj, "keywords")?;
        let author = get_str(&self.doc, &vobj, "author")?.unwrap_or_default();
        let volume = get_str(&self.doc, &vobj, "volume")?.unwrap_or_default();
        let id = get_str(&self.doc, &vobj, "id")?.unwrap_or_default();
        let created = get_str(&self.doc, &vobj, "created")?.unwrap_or_default();
        let superseded = get_bool(&self.doc, &vobj, "superseded")?.unwrap_or(false);
        Ok(Some(Version { hash: hash.to_string(), volume, id, content, tags, keywords, author, created, superseded }))
    }

    fn write_version_obj(&mut self, v: &Version) -> Result<()> {
        let (_, versions_map) = self
            .doc
            .get(automerge::ROOT, "versions")?
            .ok_or_else(|| anyhow!("versions map missing"))?;
        let vobj = self.doc.put_object(&versions_map, &v.hash, ObjType::Map)?;
        self.doc.put(&vobj, "hash", v.hash.as_str())?;
        self.doc.put(&vobj, "volume", v.volume.as_str())?;
        self.doc.put(&vobj, "id", v.id.as_str())?;
        self.doc.put(&vobj, "content", v.content.as_str())?;
        self.doc.put(&vobj, "author", v.author.as_str())?;
        self.doc.put(&vobj, "created", v.created.as_str())?;
        self.doc.put(&vobj, "superseded", v.superseded)?;
        let tags = self.doc.put_object(&vobj, "tags", ObjType::List)?;
        for t in &v.tags {
            let n = self.doc.length(&tags);
            self.doc.insert(&tags, n, t.as_str())?;
        }
        let kws = self.doc.put_object(&vobj, "keywords", ObjType::List)?;
        for k in &v.keywords {
            let n = self.doc.length(&kws);
            self.doc.insert(&kws, n, k.as_str())?;
        }
        Ok(())
    }

    fn append_hash_to_volume(&mut self, volume: &str, id: &str, hash: &str) -> Result<()> {
        let (_, volumes_map) = self
            .doc
            .get(automerge::ROOT, "volumes")?
            .ok_or_else(|| anyhow!("volumes map missing"))?;
        // ensure volume map
        let vol_obj = match self.doc.get(&volumes_map, volume)? {
            Some((_, o)) => o,
            None => self.doc.put_object(&volumes_map, volume, ObjType::Map)?,
        };
        // ensure id list
        let id_list = match self.doc.get(&vol_obj, id)? {
            Some((_, o)) => o,
            None => self.doc.put_object(&vol_obj, id, ObjType::List)?,
        };
        let n = self.doc.length(&id_list);
        self.doc.insert(&id_list, n, hash)?;
        Ok(())
    }

    fn hashes_for(&self, volume: &str, id: &str) -> Result<Vec<String>> {
        let (_, volumes_map) = self
            .doc
            .get(automerge::ROOT, "volumes")?
            .ok_or_else(|| anyhow!("volumes map missing"))?;
        let Some((_, vol_obj)) = self.doc.get(&volumes_map, volume)? else {
            return Ok(vec![]);
        };
        let Some((_, id_list)) = self.doc.get(&vol_obj, id)? else {
            return Ok(vec![]);
        };
        let len = self.doc.length(&id_list);
        let mut out = Vec::with_capacity(len);
        for i in 0..len {
            if let Some((Value::Scalar(s), _)) = self.doc.get(&id_list, i)? {
                out.push(scalar_str(s.as_ref()));
            }
        }
        Ok(out)
    }

    fn append_edge(&mut self, e: &Edge) -> Result<()> {
        let (_, edges_list) = self
            .doc
            .get(automerge::ROOT, "edges")?
            .ok_or_else(|| anyhow!("edges list missing"))?;
        let n = self.doc.length(&edges_list);
        let eobj = self.doc.insert_object(&edges_list, n, ObjType::Map)?;
        self.doc.put(&eobj, "from", e.from.as_str())?;
        self.doc.put(&eobj, "to", e.to.as_str())?;
        self.doc.put(&eobj, "kind", edge_kind_str(e.kind))?;
        self.doc.put(&eobj, "reason", e.reason.as_str())?;
        Ok(())
    }

    fn read_all_edges(&self) -> Result<Vec<Edge>> {
        let Some((_, edges_list)) = self.doc.get(automerge::ROOT, "edges")? else {
            return Ok(vec![]);
        };
        let len = self.doc.length(&edges_list);
        let mut out = Vec::with_capacity(len);
        for i in 0..len {
            let Some((_, eobj)) = self.doc.get(&edges_list, i)? else { continue };
            let from = get_str(&self.doc, &eobj, "from")?.unwrap_or_default();
            let to = get_str(&self.doc, &eobj, "to")?.unwrap_or_default();
            let kind = get_str(&self.doc, &eobj, "kind")?.unwrap_or_default();
            let reason = get_str(&self.doc, &eobj, "reason")?.unwrap_or_default();
            out.push(Edge {
                from,
                to,
                kind: parse_edge_kind(&kind).unwrap_or(EdgeKind::Parent),
                reason,
            });
        }
        Ok(out)
    }

    /// Mark a version's snapshot as superseded (flip the flag).
    fn mark_superseded(&mut self, hash: &str) -> Result<()> {
        let (_, versions_map) = self
            .doc
            .get(automerge::ROOT, "versions")?
            .ok_or_else(|| anyhow!("versions map missing"))?;
        if let Some((_, vobj)) = self.doc.get(&versions_map, hash)? {
            self.doc.put(&vobj, "superseded", true)?;
        }
        Ok(())
    }
}

impl Storage for AutomergeStorage {
    fn write(
        &mut self,
        volume: &str,
        target_id: Option<&str>,
        content: &str,
        tags: &[String],
        keywords: &[String],
        author: &str,
        intent: &str,
        refs: &[MemRef],
        typed_edges: &[Edge],
    ) -> Result<(String, String)> {
        let def = self.volume_def(volume)?;
        let now = now_iso();

        // ── Id generation: storage decides per the volume's IdStrategy. ──
        // The caller never picks the id. For a revision of an existing entry,
        // target_id carries the id to append a version to.
        let id = match target_id {
            Some(existing) => existing.to_string(),
            None => self.generate_id(volume, def.id_strategy)?,
        };

        // ── Supersede policy enforcement (engine-level, not agent semantics). ──
        // Reject any supersede edge whose target lives in a Forbidden volume.
        if def.supersede == SupersedePolicy::Forbidden {
            for e in typed_edges {
                if e.kind == EdgeKind::Supersede {
                    if let Some(tvol) = self.version_volume(&e.to)? {
                        let tdef = self.volume_def(&tvol)?;
                        if tdef.supersede == SupersedePolicy::Forbidden {
                            bail!(
                                "supersede forbidden: target {} is in volume '{}' which does not allow supersede",
                                e.to, tvol
                            );
                        }
                    }
                }
            }
        }

        let hash = Version::compute_hash(content, tags, keywords);

        // If this exact content is already stored, the version exists; still
        // record the edge (idempotent write of the same state). Exception:
        // a superseded version of this content is re-written → revive it
        // (content-addressed revive). Without this, a no-op re-mirror that
        // hit the supersede path would tombstone the entry permanently.
        let existing = self.read_version(&hash)?;
        let already = existing.is_some();
        if let Some(v) = &existing {
            if v.superseded {
                self.doc.put(&{
                    let (_, versions_map) = self
                        .doc
                        .get(automerge::ROOT, "versions")?
                        .ok_or_else(|| anyhow!("versions map missing"))?;
                    let (_, vobj) = self
                        .doc
                        .get(&versions_map, &hash)?
                        .ok_or_else(|| anyhow!("version missing"))?;
                    vobj
                }, "superseded", false)?;
            }
        }
        if !already {
            let v = Version {
                hash: hash.clone(),
                volume: volume.to_string(),
                id: id.clone(),
                content: content.to_string(),
                tags: tags.to_vec(),
                keywords: keywords.to_vec(),
                author: author.to_string(),
                created: now.clone(),
                superseded: false,
            };
            self.write_version_obj(&v)?;
        }

        // Append hash to the volume's id timeline — only for genuinely new
        // versions. An already-existing version (idempotent write or
        // content-addressed revive) must not double-append its hash or mint
        // a self-parent edge; that graph noise would corrupt lineage.
        if !already {
            self.append_hash_to_volume(volume, &id, &hash)?;

            // Auto parent edge: link to the previous version of this id, carrying intent.
            let hashes = self.hashes_for(volume, &id)?;
            if hashes.len() >= 2 {
                let prev = hashes[hashes.len() - 2].clone();
                self.append_edge(&Edge {
                    from: hash.clone(),
                    to: prev,
                    kind: EdgeKind::Parent,
                    reason: intent.to_string(),
                })?;
            } else if !intent.is_empty() {
                // Root version: record intent on a self-parent stub for retrieval.
                self.append_edge(&Edge {
                    from: hash.clone(),
                    to: hash.clone(),
                    kind: EdgeKind::Parent,
                    reason: intent.to_string(),
                })?;
            }
        }

        // Typed edges (horizontal). A supersede marks the target superseded.
        for e in typed_edges {
            let mut e = e.clone();
            e.from = hash.clone();
            self.append_edge(&e)?;
            if e.kind == EdgeKind::Supersede {
                self.mark_superseded(&e.to)?;
            }
        }

        // refs carried on the version snapshot (knowledge-graph layer).
        if !refs.is_empty() {
            let (_, versions_map) = self
                .doc
                .get(automerge::ROOT, "versions")?
                .ok_or_else(|| anyhow!("versions map missing"))?;
            if let Some((_, vobj)) = self.doc.get(&versions_map, &hash)? {
                let refs_list = match self.doc.get(&vobj, "refs")? {
                    Some((_, o)) => o,
                    None => self.doc.put_object(&vobj, "refs", ObjType::List)?,
                };
                for r in refs {
                    let n = self.doc.length(&refs_list);
                    let robj = self.doc.insert_object(&refs_list, n, ObjType::Map)?;
                    self.doc.put(&robj, "target", r.target.as_str())?;
                    self.doc.put(&robj, "reason", r.reason.as_str())?;
                    self.doc.put(&robj, "source", r.source.as_str())?;
                }
            }
        }

        Ok((id, hash))
    }

    fn declare_volume(&mut self, volume: &str, def: &VolumeDef) -> Result<()> {
        let (_, defs_map) = self
            .doc
            .get(automerge::ROOT, "volumedefs")?
            .ok_or_else(|| anyhow!("volumedefs map missing"))?;
        let dobj = match self.doc.get(&defs_map, volume)? {
            Some((_, o)) => o,
            None => self.doc.put_object(&defs_map, volume, ObjType::Map)?,
        };
        self.doc.put(&dobj, "id_strategy", id_strategy_str(def.id_strategy))?;
        self.doc.put(&dobj, "supersede", supersede_str(def.supersede))?;
        Ok(())
    }

    fn volume_def(&self, volume: &str) -> Result<VolumeDef> {
        let Some((_, defs_map)) = self.doc.get(automerge::ROOT, "volumedefs")? else {
            return Ok(VolumeDef::default());
        };
        let Some((_, dobj)) = self.doc.get(&defs_map, volume)? else {
            return Ok(VolumeDef::default());
        };
        let id_strategy = get_str(&self.doc, &dobj, "id_strategy")?
            .and_then(|s| parse_id_strategy(&s))
            .unwrap_or_default();
        let supersede = get_str(&self.doc, &dobj, "supersede")?
            .and_then(|s| parse_supersede(&s))
            .unwrap_or_default();
        Ok(VolumeDef { id_strategy, supersede })
    }

    fn materialize(&self, volume: &str, id: &str) -> Result<Option<Entry>> {
        let Some(hash) = self.latest_hash(volume, id)? else {
            return Ok(None);
        };
        let Some(v) = self.read_version(&hash)? else {
            return Ok(None);
        };
        // Read refs off the version object if present.
        let refs = self.read_version_refs(&hash)?;
        Ok(Some(Entry {
            id: format!("{}:{}", volume, id),
            volume: v.volume,
            content: v.content,
            tags: v.tags,
            keywords: v.keywords,
            author: v.author,
            created: v.created.clone(),
            updated: v.created,
            hash: v.hash,
            refs,
            refs_removed: Vec::new(),
            archived_at: None,
            archived_reason: None,
        }))
    }

    fn lineage(&self, volume: &str, id: &str) -> Result<Vec<LineageStep>> {
        let hashes = self.hashes_for(volume, id)?;
        if hashes.is_empty() {
            return Ok(vec![]);
        }
        // Build intent lookup from parent edges keyed by `from`.
        let edges = self.read_all_edges()?;
        let mut intent_for: HashMap<String, String> = HashMap::new();
        for e in &edges {
            if e.kind == EdgeKind::Parent {
                intent_for.entry(e.from.clone()).or_default().push_str(&e.reason);
            }
        }
        // Newest-first.
        let mut out = Vec::with_capacity(hashes.len());
        for h in hashes.into_iter().rev() {
            if let Some(v) = self.read_version(&h)? {
                let intent = intent_for.get(&h).cloned().unwrap_or_default();
                out.push(LineageStep { version: v, intent });
            }
        }
        Ok(out)
    }

    fn edges_from(&self, hash: &str) -> Result<Vec<Edge>> {
        Ok(self.read_all_edges()?.into_iter().filter(|e| e.from == hash).collect())
    }

    fn edges_to(&self, hash: &str) -> Result<Vec<Edge>> {
        Ok(self.read_all_edges()?.into_iter().filter(|e| e.to == hash).collect())
    }

    fn list(&self, volume: &str) -> Result<Vec<String>> {
        let (_, volumes_map) = self
            .doc
            .get(automerge::ROOT, "volumes")?
            .ok_or_else(|| anyhow!("volumes map missing"))?;
        let Some((_, vol_obj)) = self.doc.get(&volumes_map, volume)? else {
            return Ok(vec![]);
        };
        let ids: Vec<String> = self.doc.keys(&vol_obj).collect();
        Ok(ids)
    }

    fn save(&mut self) -> Result<Vec<u8>> {
        Ok(self.doc.save())
    }

    fn find_by_tag(&self, volume: &str, tags: &[String]) -> Result<Vec<Entry>> {
        let ids = self.list(volume)?;
        let mut out = Vec::new();
        for id in ids {
            if let Some(entry) = self.materialize(volume, &id)? {
                // Match if entry has ALL the requested tags.
                if tags.iter().all(|t| entry.tags.contains(t)) {
                    out.push(entry);
                }
            }
        }
        Ok(out)
    }

    fn volume_names(&self) -> Result<Vec<String>> {
        let Some((_, volumes_map)) = self.doc.get(automerge::ROOT, "volumes")? else {
            return Ok(vec![]);
        };
        Ok(self.doc.keys(&volumes_map).collect())
    }
}

impl AutomergeStorage {
    fn read_version_refs(&self, hash: &str) -> Result<Vec<MemRef>> {
        let (_, versions_map) = self
            .doc
            .get(automerge::ROOT, "versions")?
            .ok_or_else(|| anyhow!("versions map missing"))?;
        let Some((_, vobj)) = self.doc.get(&versions_map, hash)? else {
            return Ok(vec![]);
        };
        let Some((_, refs_obj)) = self.doc.get(&vobj, "refs")? else {
            return Ok(vec![]);
        };
        let len = self.doc.length(&refs_obj);
        let mut out = Vec::with_capacity(len);
        for i in 0..len {
            let Some((_, robj)) = self.doc.get(&refs_obj, i)? else { continue };
            let target = get_str(&self.doc, &robj, "target")?.unwrap_or_default();
            let reason = get_str(&self.doc, &robj, "reason")?.unwrap_or_default();
            let source = get_str(&self.doc, &robj, "source")?.unwrap_or_default();
            out.push(MemRef { target, reason, source });
        }
        Ok(out)
    }

    /// Generate a new id for a volume per its IdStrategy.
    /// Sequential: next ordinal (`"65"`). Random: 4-hex-char hash.
    fn generate_id(&self, volume: &str, strategy: IdStrategy) -> Result<String> {
        match strategy {
            IdStrategy::Sequential => {
                let existing = self.list(volume)?;
                let max = existing
                    .iter()
                    .filter_map(|id| id.parse::<usize>().ok())
                    .max()
                    .unwrap_or(0);
                Ok(format!("{}", max + 1))
            }
            IdStrategy::Random => {
                use std::time::{SystemTime, UNIX_EPOCH};
                let nanos = SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .map(|d| d.subsec_nanos())
                    .unwrap_or(0);
                let folded = (nanos ^ (nanos >> 16) ^ (nanos >> 24)) & 0xFFFF;
                Ok(format!("{:04x}", folded))
            }
        }
    }

    /// Look up which volume a version hash belongs to (for supersede checks).
    fn version_volume(&self, hash: &str) -> Result<Option<String>> {
        Ok(self.read_version(hash)?.map(|v| v.volume))
    }
}

// ─── strategy helpers ──────────────────────────────────────────────────────

fn id_strategy_str(s: IdStrategy) -> &'static str {
    match s {
        IdStrategy::Sequential => "sequential",
        IdStrategy::Random => "random",
    }
}

fn parse_id_strategy(s: &str) -> Option<IdStrategy> {
    match s {
        "sequential" => Some(IdStrategy::Sequential),
        "random" => Some(IdStrategy::Random),
        _ => None,
    }
}

fn supersede_str(s: SupersedePolicy) -> &'static str {
    match s {
        SupersedePolicy::Allowed => "allowed",
        SupersedePolicy::Forbidden => "forbidden",
    }
}

fn parse_supersede(s: &str) -> Option<SupersedePolicy> {
    match s {
        "allowed" => Some(SupersedePolicy::Allowed),
        "forbidden" => Some(SupersedePolicy::Forbidden),
        _ => None,
    }
}

// ─── helpers ───────────────────────────────────────────────────────────────

fn now_iso() -> String {
    chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

fn edge_kind_str(k: EdgeKind) -> &'static str {
    match k {
        EdgeKind::Parent => "parent",
        EdgeKind::Supersede => "supersede",
        EdgeKind::DeriveFrom => "derive_from",
        EdgeKind::Validate => "validate",
        EdgeKind::Constrain => "constrain",
    }
}

fn parse_edge_kind(s: &str) -> Option<EdgeKind> {
    match s {
        "parent" => Some(EdgeKind::Parent),
        "supersede" => Some(EdgeKind::Supersede),
        "derive_from" => Some(EdgeKind::DeriveFrom),
        "validate" => Some(EdgeKind::Validate),
        "constrain" => Some(EdgeKind::Constrain),
        _ => None,
    }
}

fn scalar_str(v: &automerge::ScalarValue) -> String {
    match v {
        automerge::ScalarValue::Str(s) => s.to_string(),
        automerge::ScalarValue::Int(i) => i.to_string(),
        automerge::ScalarValue::Boolean(b) => b.to_string(),
        other => format!("{:?}", other),
    }
}

fn get_str(doc: &AutoCommit, obj: &automerge::ObjId, key: &str) -> Result<Option<String>> {
    Ok(doc
        .get(obj, key)?
        .and_then(|(v, _)| match v {
            Value::Scalar(s) => Some(scalar_str(s.as_ref())),
            _ => None,
        }))
}

fn get_bool(doc: &AutoCommit, obj: &automerge::ObjId, key: &str) -> Result<Option<bool>> {
    Ok(doc.get(obj, key)?.and_then(|(v, _)| match v {
        Value::Scalar(s) => match s.as_ref() {
            automerge::ScalarValue::Boolean(b) => Some(*b),
            _ => None,
        },
        _ => None,
    }))
}

fn get_list_strings(doc: &AutoCommit, obj: &automerge::ObjId, key: &str) -> Result<Vec<String>> {
    let Some((_, list)) = doc.get(obj, key)? else {
        return Ok(vec![]);
    };
    let len = doc.length(&list);
    let mut out = Vec::with_capacity(len);
    for i in 0..len {
        if let Some((Value::Scalar(s), _)) = doc.get(&list, i)? {
            out.push(scalar_str(s.as_ref()));
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sequential_id_increments() {
        let mut s = AutomergeStorage::new();
        s.declare_volume("active", &VolumeDef::default()).unwrap();
        let (id1, _) = s.write("active", None, "first", &[], &[], "a", "init", &[], &[]).unwrap();
        let (id2, _) = s.write("active", None, "second", &[], &[], "a", "init", &[], &[]).unwrap();
        assert_eq!(id1, "1");
        assert_eq!(id2, "2");
    }

    #[test]
    fn random_id_is_hex() {
        let mut s = AutomergeStorage::new();
        s.declare_volume("draft", &VolumeDef {
            id_strategy: IdStrategy::Random,
            supersede: SupersedePolicy::Allowed,
        })
        .unwrap();
        let (id, _) = s.write("draft", None, "x", &[], &[], "a", "init", &[], &[]).unwrap();
        assert!(id.chars().all(|c| c.is_ascii_hexdigit()), "random id should be hex, got {}", id);
        assert_ne!(id.parse::<usize>().ok(), Some(1), "random id should not be sequential 1");
    }

    #[test]
    fn supersede_forbidden_rejects_supersede() {
        let mut s = AutomergeStorage::new();
        // handover: audit trail, no overturning allowed
        s.declare_volume("handover", &VolumeDef {
            id_strategy: IdStrategy::Sequential,
            supersede: SupersedePolicy::Forbidden,
        })
        .unwrap();
        let (_, h1) = s.write("handover", None, "session 1 log", &[], &[], "a", "log", &[], &[]).unwrap();
        // Attempt to supersede the handover entry — must be rejected.
        let supersede_edge = Edge {
            from: String::new(),
            to: h1.clone(),
            kind: EdgeKind::Supersede,
            reason: "try to overturn audit".into(),
        };
        let result = s.write("handover", Some("1"), "overturn attempt", &[], &[], "a", "bad", &[], &[supersede_edge]);
        assert!(result.is_err(), "supersede must be rejected in a Forbidden volume");
    }

    #[test]
    fn supersede_allowed_accepts_supersede() {
        let mut s = AutomergeStorage::new();
        s.declare_volume("layer", &VolumeDef::default()).unwrap();
        let (_, h1) = s.write("layer", Some("1"), "v1 claim", &[], &[], "a", "init", &[], &[]).unwrap();
        let supersede_edge = Edge {
            from: String::new(),
            to: h1,
            kind: EdgeKind::Supersede,
            reason: "v1 was wrong".into(),
        };
        let result = s.write("layer", Some("1"), "v2 corrected", &[], &[], "a", "fix", &[], &[supersede_edge]);
        assert!(result.is_ok(), "supersede allowed in default volume");
    }

    #[test]
    fn find_by_tag_matches_all() {
        let mut s = AutomergeStorage::new();
        s.write("meta", Some("1"), "## A", &["type:design".into(), "module:core".into()], &[], "a", "i", &[], &[]).unwrap();
        s.write("meta", Some("2"), "## B", &["type:design".into(), "module:auth".into()], &[], "a", "i", &[], &[]).unwrap();
        s.write("meta", Some("3"), "## C", &["type:handoff".into()], &[], "a", "i", &[], &[]).unwrap();

        // AND filter: both tags
        let both = s.find_by_tag("meta", &["type:design".into(), "module:core".into()]).unwrap();
        assert_eq!(both.len(), 1);
        assert_eq!(both[0].id, "meta:1");

        let design = s.find_by_tag("meta", &["type:design".into()]).unwrap();
        assert_eq!(design.len(), 2);
    }

    #[test]
    fn volume_def_defaults_when_undeclared() {
        let s = AutomergeStorage::new();
        let def = s.volume_def("anything").unwrap();
        assert_eq!(def.id_strategy, IdStrategy::Sequential);
        assert_eq!(def.supersede, SupersedePolicy::Allowed);
    }
}
