#!/usr/bin/env node
// Stellario CLI — pure JS, no build step needed
// This file is the npm bin entry point

import { existsSync, mkdirSync, writeFileSync, cpSync, readFileSync } from "fs"
import { join, resolve, dirname } from "path"
import { execSync } from "child_process"
import { fileURLToPath } from "url"
import { parse as parseYaml } from "yaml"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const TEMPLATES = ["minimal", "novel", "software", "audit"]

// Glue files are shipped in glue/ directory — no inline templates needed.
// Mapping: glue source filename → target filename in .opencode/tools/
const GLUE_FILES = {
  "memory.ts": "stellario-memory.ts",
  "telescope.ts": "stellario-telescope.ts",
  "workspace.ts": "stellario-workspace.ts",
  "volume-link.ts": "stellario-volume-link.ts",
}

// ── Main ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2)
const command = args[0]

if (!command || command === "help" || command === "--help") {
  console.log(`stellario — agent memory infrastructure

Usage:
  stellario init [--template <name>] [--root <path>]

Commands:
  init    Initialize Stellario in a project

Options:
  -t, --template <name>   Config template: ${TEMPLATES.join(", ")} (default: minimal)
      --root <path>       Project root directory (default: current directory)

Examples:
  npx github:FadingRose/stellario init --template software
  npx stellario init --template novel --root /path/to/project
`)
  process.exit(0)
}

if (command !== "init") {
  console.error(`Unknown command: ${command}`)
  process.exit(1)
}

// ── Init ──────────────────────────────────────────────────────────────────

const template = getArg(args, "--template") || getArg(args, "-t") || "minimal"
const projectRoot = resolve(getArg(args, "--root") || ".")

if (!TEMPLATES.includes(template)) {
  console.error(`Unknown template: "${template}". Available: ${TEMPLATES.join(", ")}`)
  process.exit(1)
}

if (!existsSync(projectRoot)) {
  console.error(`Directory not found: ${projectRoot}`)
  process.exit(1)
}

console.log(`Stellario init — template: ${template}`)
console.log(`Project root: ${projectRoot}`)
console.log("")

const opencodeDir = join(projectRoot, ".opencode")
const configPath = join(opencodeDir, "stellario.yaml")

// ── 1. Config ──────────────────────────────────────────────────────────────

const packageRoot = resolve(join(__dirname, "..", ".."))

if (existsSync(configPath)) {
  console.log(`⚠  Config already exists: ${configPath} (skipped)`)
} else {
  const templatePath = join(packageRoot, "templates", `${template}.yaml`)

  if (!existsSync(templatePath)) {
    console.error(`Template not found: ${templatePath}`)
    console.error(`Available templates: ${TEMPLATES.join(", ")}`)
    process.exit(1)
  }

  mkdirSync(opencodeDir, { recursive: true })
  cpSync(templatePath, configPath)
  console.log(`✓ Config: ${configPath}`)
}

// ── 2. Load config ─────────────────────────────────────────────────────────

const config = parseYaml(readFileSync(configPath, "utf-8"))
const agents = Object.keys(config.agents || {})
const volumes = config.volumes || {}

// ── 3. Memory directory + git init ─────────────────────────────────────────

const memDir = join(projectRoot, config.memoryDir || ".opencode/.stellario")
if (!existsSync(memDir)) {
  mkdirSync(memDir, { recursive: true })
  console.log(`✓ Memory dir: ${memDir}`)
}

if (!existsSync(join(memDir, ".git"))) {
  try {
    execSync("git init", { cwd: memDir, stdio: "pipe" })
    console.log(`✓ Memory git init`)
  } catch {
    console.log(`⚠  git init failed in ${memDir}`)
  }
} else {
  console.log(`  Memory git: already initialized`)
}

// .gitignore inside memDir (exclude generated index files)
const memGitignore = join(memDir, ".gitignore")
if (!existsSync(memGitignore)) {
  writeFileSync(memGitignore, "# Generated by Stellario — do not edit\nkeywords-index.jsonl\n")
  console.log(`✓ Memory .gitignore: created`)
} else {
  const gi = readFileSync(memGitignore, "utf-8")
  if (!gi.includes("keywords-index.jsonl")) {
    writeFileSync(memGitignore, gi.trimEnd() + "\nkeywords-index.jsonl\n")
    console.log(`✓ Memory .gitignore: added keywords-index.jsonl`)
  }
}

// ── 4. package.json ────────────────────────────────────────────────────────

const pkgPath = join(opencodeDir, "package.json")
let needsInstall = false

if (!existsSync(pkgPath)) {
  const version = getStellarioVersion()
  const stellarioDep = version === "latest" ? "latest" : `^${version}`
  const pkg = {
    private: true,
    dependencies: {
      "@opencode-ai/plugin": "latest",
      zod: "^3.23.0",
      stellario: stellarioDep,
    },
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n")
  needsInstall = true
  console.log(`✓ package.json: created`)
} else {
  const existingPkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
  const deps = existingPkg.dependencies || {}
  if (!deps.stellario) {
    const version = getStellarioVersion()
    deps.stellario = version === "latest" ? "latest" : `^${version}`
    existingPkg.dependencies = deps
    writeFileSync(pkgPath, JSON.stringify(existingPkg, null, 2) + "\n")
    needsInstall = true
    console.log(`✓ package.json: added stellario dependency`)
  } else {
    console.log(`  package.json: stellario already listed`)
  }
}

// ── 5. Glue files (copied from shipped glue/ directory) ──────────────────────

const toolsDir = join(opencodeDir, "tools")
mkdirSync(toolsDir, { recursive: true })

const glueDir = join(packageRoot, "glue")
for (const [src, dest] of Object.entries(GLUE_FILES)) {
  const srcPath = join(glueDir, src)
  const destPath = join(toolsDir, dest)
  if (existsSync(destPath)) {
    console.log(`  Tools: ${dest} (exists, skipped)`)
  } else {
    cpSync(srcPath, destPath)
    console.log(`✓ Tools: ${dest}`)
  }
}

// ── 5b. Plugin injector ─────────────────────────────────────────────────────

const pluginDir = join(opencodeDir, "plugin")
mkdirSync(pluginDir, { recursive: true })
const pluginSrc = join(glueDir, "plugin.ts")
const pluginDest = join(pluginDir, "stellario-inject.ts")
if (existsSync(pluginDest)) {
  console.log(`  Plugin: stellario-inject.ts (exists, skipped)`)
} else {
  cpSync(pluginSrc, pluginDest)
  console.log(`✓ Plugin: stellario-inject.ts`)
}

// ── 6. Agent: stellario guide ─────────────────────────────────────────────

const agentsDir = join(opencodeDir, "agents")
mkdirSync(agentsDir, { recursive: true })

const allVolumeNames = Object.keys(volumes)
const stellarioAgentPath = join(agentsDir, "stellario.md")

if (existsSync(stellarioAgentPath)) {
  console.log(`  Guide: stellario.md (exists, skipped)`)
} else {
  const memoryTools = ["stellario-memory_create", "stellario-memory_show", "stellario-memory_revise", "stellario-memory_forget", "stellario-memory_history", "stellario-memory_meta", "stellario-memory_ref", "stellario-memory_unref"]
  const searchTools = ["stellario-telescope_search"]
  const workspaceTools = ["stellario-workspace_status", "stellario-workspace_assemble", "stellario-workspace_open", "stellario-workspace_edit", "stellario-workspace_add", "stellario-workspace_remove"]
  const volumeLinkTools = ["stellario-volume-link_discover", "stellario-volume-link_link", "stellario-volume-link_unlink"]

  const stellarioTools = [
    ...memoryTools,
    ...searchTools,
    ...workspaceTools,
    ...volumeLinkTools,
  ].map(t => `  ${t}: true`).join("\n")

  const stellarioContent = `---
description: Stellario
mode: primary
tools:
${stellarioTools}
---

# Stellario

You are the memory guide. You manage the Stellario memory system and scaffold other agents.

## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \`status\` to bootstrap.

## When Memory Is Empty

If you see "Memory: empty" in the injected status, this is a fresh install. Run through the demo sequence below, then guide the user through agent creation.

---

## Phase 1: Demo

Do NOT ask the user questions during this phase. Execute all steps yourself, narrating what you're doing and why. Use the project's actual config (volumes, agents) as demo context.

### Demo 1: Create — write memory (and permissions)

Pick the first mutable volume from the config that has a write boundary. Try to create an entry:

\`\`\`
create(volume="{first_mutable_volume}", content="## Project: Stellario Playground\\nA test project for exploring agent memory.", tags=["type:overview"], keywords=["playground", "overview"])
\`\`\`

**If you get a permission error (forbidden):** This is expected! You are \\\`stellario\\\`, and the config may not include \\\`stellario\\\` in the volume's \\\`boundaries.write\\\`. This is by design — permissions are config-driven.

Fix it immediately: use the \\\`edit\\\` tool to add \\\`stellario\\\` to the write (and read) boundaries of the relevant volumes in \\\`.opencode/stellario.yaml\\\`. Then retry the \\\`create\\\`.

Explain to the user:
- Every volume has \\\`boundaries\\\` that define which agents can read/write
- If an agent is not listed, the operation is forbidden
- Fixing permissions is as simple as editing the config — changes take effect immediately
- This is the security model: agents can only do what the config explicitly allows

Then create a second entry in the same volume:

\`\`\`
create(volume="{first_mutable_volume}", content="## Convention: Tag Namespace\\nAll tags use namespace:name format (e.g. type:design, severity:high).", tags=["type:convention"], keywords=["tags", "namespace"])
\`\`\`

Explain: entries live in volumes. Each volume has a profile (mutable, append, scratch, frozen, workspace). Mutable volumes allow revisions and archival. Every entry is git-tracked.

### Demo 2: Revise — edit memory

Revise the first entry to add more detail:

\`\`\`
show(id="{first_entry_id}")
revise(id="{first_entry_id}", from=1, to=1, content="## Project: Stellario Playground\\nA test project for exploring structured, permissioned, version-controlled agent memory.", message="add more detail to project description")
\`\`\`

Explain: revise uses line ranges (1-indexed). The old version is preserved in git history — nothing is truly lost.

### Demo 3: Ref — build knowledge graph

Link the two entries:

\`\`\`
ref(id="{first_entry_id}", target="{second_entry_id}", reason="tagging convention applies to this project")
\`\`\`

Explain: refs are manual edges in a knowledge graph. There's also an auto-refs engine that can link entries based on tag/keyword overlap.

### Demo 4: Search — find memory

Run three searches to show different modes:

\`\`\`
search(query="namespace")                        # text search
search(tags=["type:convention"])                  # tag filter
search(query="how should I organize my data")     # semantic search (finds "tags" without keyword match)
\`\`\`

Explain: hybrid search combines text matching with semantic embedding. Tags filter precisely. Keywords enable concept-level discovery — searching "organize data" can find an entry about "tag namespace" even without word overlap.

### Demo 5: Workspace — gather context

Assemble the entries into a workspace theme:

\`\`\`
assemble(content="## Playground Setup\\nGetting started with Stellario memory", entries=["{id1}", "{id2}"])
open()
\`\`\`

Explain: workspace tracks your active context across sessions. \\\`assemble\\\` gathers entries, \\\`open\\\` expands them inline. Only one workspace volume per project.

### Demo 6: Shared Memory — multi-agent collaboration

This is the most important demo. Show how multiple agents collaborate through shared volumes.

1. Pick the first agent from the config that is NOT \\\`stellario\\\` (any agent with a defined role). If the config has no other agents besides yourself, explain the concept and skip the interactive part.
2. **Generate that agent's file now** — create \\\`.opencode/agents/{name}.md\\\` following the Agent Construction Rules (see Phase 2). This is a one-time early generation so the demo works.
3. Pick a volume that the target agent can read (check \\\`boundaries.read\\\`). Write a message to that agent:

\`\`\`
create(volume="{shared_volume}", content="## Task for {agent_name}\\n{agent_name}, please analyze the project's memory structure and leave your observations here.", tags=["type:task", "for:{agent_name}"], keywords=["collaboration", "task"])
\`\`\`

4. Show the user the volume's \\\`boundaries\\\` from the config — point out that \\\`{agent_name}\\\` is in the read list (and write list if applicable).
5. Tell the user: **"Now open a new opencode session and switch to the {agent_name} agent."** Wait for them.
6. Once the user returns, ask them what {agent_name} saw and did. Then demonstrate reading {agent_name}'s response:

\`\`\`
search(query="{agent_name}")
\`\`\`

Explain: this is the core collaboration model. Agents don't talk to each other directly — they share context through volumes. Any agent with read access to a volume can see everything there. Agents with write access can leave messages and observations. This is how multi-agent coordination works without any message-passing infrastructure.

### Demo 7: Volume Link — cross-project observation

Demonstrate linking an external Stellario project:

1. Create a temporary project: use bash to create \\\`/tmp/stellario-kb-demo/.opencode/.stellario/\\\` with a minimal \\\`stellario.yaml\\\` (one volume \\\`kb\\\`) and a JSONL file with 2-3 knowledge entries (e.g. design patterns, debugging tips)
2. Run \\\`discover(path="/tmp/stellario-kb-demo")\\\` to see what's available
3. Run \\\`link(project="/tmp/stellario-kb-demo", volume="kb", alias="knowledge-base")\\\`
4. Run \\\`search(query="design pattern")\\\` to show results now span both projects
5. Run \\\`unlink(volume="kb")\\\` to clean up
6. Use bash to delete \\\`/tmp/stellario-kb-demo\\\`

Explain: linked volumes are readonly symlinks. You observe without modifying. This is how a project can reference a shared knowledge base, or how an audit can observe a client project's memory without touching it.

### Demo 8: Meta — behavioral calibration

Create a meta entry that persists across sessions:

\`\`\`
meta(content="Always confirm before archiving entries. Keep the playground clean.")
\`\`\`

Explain: meta entries with tag \\\`type:prompt\\\` are auto-injected into your system context on every session start. Use them for behavioral calibrations that outlive any single conversation.

### Handoff: session continuity

Now write a handoff summarizing what was done in this session:

\`\`\`
create(volume="handover", content="## Handoff: First Session\\nCompleted Stellario demo. Created 2 entries, linked with ref, demonstrated search/workspace/volume link/shared memory/meta. User has not yet done Phase 2 setup.", tags=["type:handoff"], keywords=["handoff", "first-session"])
\`\`\`

Explain: the \\\`handover\\\` volume is append-only — entries cannot be revised or deleted. This is intentional: handoffs are immutable records. On the next session start, the plugin injects the latest handover entry into the system context, so the next version of me knows exactly where we left off.

**Important habit to teach the user:** When the context window is getting long or the session is wrapping up, do a handoff. Write what was done, what's in progress, what's blocked, and what's next. This is how agents survive across sessions — every primary agent should hand off before a session ends.

---

## Phase 2: Setup

After the demo, guide the user through setting up their project:

1. **Ask about the project** — What are you working on? What kind of memory do you need?
2. **Generate agent files** — Read \`.opencode/stellario.yaml\`, create \`.opencode/agents/{name}.md\` for every agent defined in the config (except yourself and any agent already generated during Demo 6). See Agent Construction Rules below.
3. **First real entries** — Help the user write their first meaningful memory entries based on their project context

### Agent Construction Rules

When generating agent files, use the \\\`edit\\\` tool to write each \\\`.opencode/agents/{name}.md\\\`. Follow these rules:

**Frontmatter:**

| Field | Value |
|-------|-------|
| \\\`description\\\` | \\\`agent.display\\\` from config, or the agent name |
| \\\`mode\\\` | \\\`primary\\\` if \\\`role: primary\\\`, otherwise \\\`subagent\\\` |
| \\\`tools\\\` | See tool assignment below |

**Tool assignment:**

1. If \\\`role: primary\\\` → include \\\`task: true\\\`, \\\`edit: true\\\`, \\\`bash: true\\\`
2. If the agent has **write** access to **any** volume (check \\\`volumes.{name}.boundaries.write\\\`) → give all memory tools
3. If the agent has **no write** access → only \\\`stellario-memory_show\\\` and \\\`stellario-memory_history\\\`
4. All agents get: search, workspace, volume-link tools

**Body — keep minimal:**

\`\`\`markdown
# {display}

You are a memory-aware agent powered by Stellario.

## Available Volumes

{list of volumes this agent can read or write}
\`\`\`

For primary agents, also add:

\`\`\`markdown
## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \\\`status\\\` to bootstrap.

## Handoff

When the context window is getting long or the session is wrapping up, write a handoff to the \\\`handover\\\` volume:

\`\`\\\`
create(volume="handover", content="## Handoff: {summary}\\nWhat was done, what's in progress, what's blocked, what's next.", tags=["type:handoff"], keywords=["handoff"])
\`\`\\\`

Handoffs are append-only immutable records. The next session's agent reads the latest handoff to continue seamlessly.
\`\`\`

---

## User Introduction

Fill this in during the first conversation. Update whenever the user's needs change.

<!-- INTRODUCTION_START -->
## About the User

*(Not yet filled in — ask during Phase 2)*
<!-- INTRODUCTION_END -->

## Memory Philosophy

- Write to memory when you learn something worth remembering across sessions
- Use \\\`meta\\\` for behavioral calibrations (injected as prompts)
- Use append volumes for handoff logs (immutable records)
- Use scratch volumes for temporary drafts (not git-tracked)
- Use \\\`workspace_assemble\\\` to gather related entries into a focused context
- Use \\\`ref\\\` / \\\`unref\\\` for manual knowledge graph edges
- Use \\\`discover\\\` / \\\`link\\\` to observe other projects' memory

## Available Volumes

${allVolumeNames.map(v => `- ${v}`).join("\n")}
`
  writeFileSync(stellarioAgentPath, stellarioContent)
  console.log(`✓ Guide: stellario.md`)
}

// ── 7. npm install ─────────────────────────────────────────────────────────

if (needsInstall) {
  console.log("")
  console.log("Installing dependencies in .opencode/...")
  try {
    execSync("npm install", { cwd: opencodeDir, stdio: "pipe" })
    console.log("✓ npm install")
  } catch {
    console.log(`⚠  npm install failed. Run manually: cd .opencode && npm install`)
  }
}

// ── 8. .gitignore ──────────────────────────────────────────────────────────

const gitignorePath = join(projectRoot, ".gitignore")
if (existsSync(gitignorePath)) {
  const gitignore = readFileSync(gitignorePath, "utf-8")
  if (!gitignore.includes(".opencode/")) {
    writeFileSync(gitignorePath, gitignore.trimEnd() + "\n.opencode/\n")
    console.log(`✓ .gitignore: added .opencode/`)
  }
} else {
  writeFileSync(gitignorePath, ".opencode/\n")
  console.log(`✓ .gitignore: created`)
}

console.log("")
console.log("Done! Next steps:")
console.log(`  1. Edit .opencode/stellario.yaml to customize`)
console.log(`  2. Create type:prompt entries in meta volume for dynamic prompts`)
console.log(`  3. Start opencode — tools, plugin, and prompts auto-discovered`)

// ── Helpers ────────────────────────────────────────────────────────────────

function getArg(args, flag) {
  const idx = args.indexOf(flag)
  if (idx === -1 || idx + 1 >= args.length) return undefined
  return args[idx + 1]
}

function getStellarioVersion() {
  try {
    const pkgPath = resolve(join(__dirname, "..", "..", "package.json"))
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
    return pkg.version || "latest"
  } catch {
    return "latest"
  }
}

