#!/usr/bin/env node
// Stellario CLI — pure JS, no build step needed
// This file is the npm bin entry point

import { existsSync, mkdirSync, writeFileSync, cpSync, readFileSync } from "fs"
import { join, resolve, dirname } from "path"
import { execSync } from "child_process"
import { fileURLToPath } from "url"
import { parse as parseYaml } from "yaml"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const TEMPLATES = ["minimal", "novel", "software", "audit"]

// Glue files are shipped in glue/ directory — no inline templates needed.
// Mapping: glue source filename → target filename in .opencode/tools/
const GLUE_FILES = {
  "memory.ts": "stellario-memory.ts",
  "telescope.ts": "stellario-telescope.ts",
  "workspace.ts": "stellario-workspace.ts",
  "volume-link.ts": "stellario-volume-link.ts",
}

// ── Main ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2)
const command = args[0]

if (!command || command === "help" || command === "--help") {
  console.log(`stellario — agent memory infrastructure

Usage:
  stellario init [--template <name>] [--root <path>]

Commands:
  init    Initialize Stellario in a project

Options:
  -t, --template <name>   Config template: ${TEMPLATES.join(", ")} (default: minimal)
      --root <path>       Project root directory (default: current directory)

Examples:
  npx github:FadingRose/stellario init --template software
  npx stellario init --template novel --root /path/to/project
`)
  process.exit(0)
}

if (command !== "init") {
  console.error(`Unknown command: ${command}`)
  process.exit(1)
}

// ── Init ──────────────────────────────────────────────────────────────────

const template = getArg(args, "--template") || getArg(args, "-t") || "minimal"
const projectRoot = resolve(getArg(args, "--root") || ".")

if (!TEMPLATES.includes(template)) {
  console.error(`Unknown template: "${template}". Available: ${TEMPLATES.join(", ")}`)
  process.exit(1)
}

if (!existsSync(projectRoot)) {
  console.error(`Directory not found: ${projectRoot}`)
  process.exit(1)
}

console.log(`Stellario init — template: ${template}`)
console.log(`Project root: ${projectRoot}`)
console.log("")

const opencodeDir = join(projectRoot, ".opencode")
const configPath = join(opencodeDir, "stellario.yaml")

// ── 1. Config ──────────────────────────────────────────────────────────────

const packageRoot = resolve(join(__dirname, "..", ".."))

if (existsSync(configPath)) {
  console.log(`⚠  Config already exists: ${configPath} (skipped)`)
} else {
  const templatePath = join(packageRoot, "templates", `${template}.yaml`)

  if (!existsSync(templatePath)) {
    console.error(`Template not found: ${templatePath}`)
    console.error(`Available templates: ${TEMPLATES.join(", ")}`)
    process.exit(1)
  }

  mkdirSync(opencodeDir, { recursive: true })
  cpSync(templatePath, configPath)
  console.log(`✓ Config: ${configPath}`)
}

// ── 2. Load config ─────────────────────────────────────────────────────────

const config = parseYaml(readFileSync(configPath, "utf-8"))
const agents = Object.keys(config.agents || {})
const volumes = config.volumes || {}

// ── 3. Memory directory + git init ─────────────────────────────────────────

const memDir = join(projectRoot, config.memoryDir || ".opencode/.stellario")
if (!existsSync(memDir)) {
  mkdirSync(memDir, { recursive: true })
  console.log(`✓ Memory dir: ${memDir}`)
}

if (!existsSync(join(memDir, ".git"))) {
  try {
    execSync("git init", { cwd: memDir, stdio: "pipe" })
    console.log(`✓ Memory git init`)
  } catch {
    console.log(`⚠  git init failed in ${memDir}`)
  }
} else {
  console.log(`  Memory git: already initialized`)
}

// .gitignore inside memDir (exclude generated index files)
const memGitignore = join(memDir, ".gitignore")
if (!existsSync(memGitignore)) {
  writeFileSync(memGitignore, "# Generated by Stellario — do not edit\nkeywords-index.jsonl\n")
  console.log(`✓ Memory .gitignore: created`)
} else {
  const gi = readFileSync(memGitignore, "utf-8")
  if (!gi.includes("keywords-index.jsonl")) {
    writeFileSync(memGitignore, gi.trimEnd() + "\nkeywords-index.jsonl\n")
    console.log(`✓ Memory .gitignore: added keywords-index.jsonl`)
  }
}

// ── 4. package.json ────────────────────────────────────────────────────────

const pkgPath = join(opencodeDir, "package.json")
let needsInstall = false

if (!existsSync(pkgPath)) {
  const version = getStellarioVersion()
  const stellarioDep = version === "latest" ? "latest" : `^${version}`
  const pkg = {
    private: true,
    dependencies: {
      "@opencode-ai/plugin": "latest",
      zod: "^3.23.0",
      stellario: stellarioDep,
    },
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n")
  needsInstall = true
  console.log(`✓ package.json: created`)
} else {
  const existingPkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
  const deps = existingPkg.dependencies || {}
  if (!deps.stellario) {
    const version = getStellarioVersion()
    deps.stellario = version === "latest" ? "latest" : `^${version}`
    existingPkg.dependencies = deps
    writeFileSync(pkgPath, JSON.stringify(existingPkg, null, 2) + "\n")
    needsInstall = true
    console.log(`✓ package.json: added stellario dependency`)
  } else {
    console.log(`  package.json: stellario already listed`)
  }
}

// ── 5. Glue files (copied from shipped glue/ directory) ──────────────────────

const toolsDir = join(opencodeDir, "tools")
mkdirSync(toolsDir, { recursive: true })

const glueDir = join(packageRoot, "glue")
for (const [src, dest] of Object.entries(GLUE_FILES)) {
  const srcPath = join(glueDir, src)
  const destPath = join(toolsDir, dest)
  if (existsSync(destPath)) {
    console.log(`  Tools: ${dest} (exists, skipped)`)
  } else {
    cpSync(srcPath, destPath)
    console.log(`✓ Tools: ${dest}`)
  }
}

// ── 5b. Plugin injector ─────────────────────────────────────────────────────

const pluginDir = join(opencodeDir, "plugin")
mkdirSync(pluginDir, { recursive: true })
const pluginSrc = join(glueDir, "plugin.ts")
const pluginDest = join(pluginDir, "stellario-inject.ts")
if (existsSync(pluginDest)) {
  console.log(`  Plugin: stellario-inject.ts (exists, skipped)`)
} else {
  cpSync(pluginSrc, pluginDest)
  console.log(`✓ Plugin: stellario-inject.ts`)
}

// ── 6. Agent: stellario guide ─────────────────────────────────────────────

const agentsDir = join(opencodeDir, "agents")
mkdirSync(agentsDir, { recursive: true })

const allVolumeNames = Object.keys(volumes)
const stellarioAgentPath = join(agentsDir, "stellario.md")

if (existsSync(stellarioAgentPath)) {
  console.log(`  Guide: stellario.md (exists, skipped)`)
} else {
  const memoryTools = ["stellario-memory_create", "stellario-memory_show", "stellario-memory_revise", "stellario-memory_forget", "stellario-memory_history", "stellario-memory_meta", "stellario-memory_ref", "stellario-memory_unref"]
  const searchTools = ["stellario-telescope_search"]
  const workspaceTools = ["stellario-workspace_status", "stellario-workspace_assemble", "stellario-workspace_open", "stellario-workspace_edit", "stellario-workspace_add", "stellario-workspace_remove"]
  const volumeLinkTools = ["stellario-volume-link_discover", "stellario-volume-link_link", "stellario-volume-link_unlink"]

  const stellarioTools = [
    ...memoryTools,
    ...searchTools,
    ...workspaceTools,
    ...volumeLinkTools,
  ].map(t => `  ${t}: true`).join("\n")

  const stellarioContent = `---
description: Stellario
mode: primary
tools:
${stellarioTools}
---

# Stellario

You are the memory guide. You manage the Stellario memory system and scaffold other agents.

## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \`status\` to bootstrap.

## Step 0: Generate Agent Files

On first boot, read \`.opencode/stellario.yaml\` and create \`.opencode/agents/{name}.md\` for every agent defined in the config (except yourself — stellario.md already exists).

Use the \`edit\` tool to write each file. Follow these rules:

### Frontmatter

| Field | How to set |
|-------|-----------|
| \`description\` | \\\`agent.display\\\` from config, or the agent name |
| \`mode\` | \\\`primary\\\` if \\\`role: primary\\\`, otherwise \\\`subagent\\\` |
| \`tools\` | See tool assignment rules below |

### Tool Assignment

1. If \\\`role: primary\\\` → include \\\`task: true\\\`, \\\`edit: true\\\`, \\\`bash: true\\\`
2. If the agent has **write** access to **any** volume → give all memory tools (create, show, revise, forget, history, meta, ref, unref)
3. If the agent has **no write** access → only \\\`stellario-memory_show: true\\\` and \\\`stellario-memory_history: true\\\`
4. All agents get: search, workspace, volume-link tools

Check write access via \\\`volumes.{name}.boundaries.write\\\` in the config — if the agent name appears in any volume's write list, it has write access.

### Body

Keep it minimal. Include:

\`\`\`markdown
# {display}

You are a memory-aware agent powered by Stellario.

## Available Volumes

{list of volumes this agent can access — both read and write}
\`\`\`

For primary agents, also add:

\`\`\`markdown
## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \\\`status\\\` to bootstrap.
\`\`\`

## Step 1: Onboarding

If you see "Memory: empty" in the injected status, this is a fresh install. Walk the user through:

1. **Greet & Learn** — Ask what they're working on and what kind of memory they need
2. **First Entry** — Create a memory entry to demonstrate the core flow
3. **Second Entry + Ref** — Create a related entry, link them with \`ref\`
4. **Search** — Demonstrate text + semantic + tag search
5. **Workspace** — \`assemble\` a theme, then \`open\` it
6. **Meta Calibration** — Create a behavioral prompt that persists across sessions
7. **Volume Link** (optional) — If the user has other stellario projects

## User Introduction

Fill this in during the first conversation. Update whenever the user's needs change.

<!-- INTRODUCTION_START -->
## About the User

*(Not yet filled in — ask during onboarding)*
<!-- INTRODUCTION_END -->

## Memory Philosophy

- Write to memory when you learn something worth remembering across sessions
- Use \`meta\` for behavioral calibrations (injected as prompts)
- Use append volumes for handoff logs (immutable records)
- Use scratch volumes for temporary drafts (not git-tracked)
- Use \`workspace_assemble\` to gather related entries into a focused context
- Use \`ref\` / \`unref\` for manual knowledge graph edges
- Use \`discover\` / \`link\` to observe other projects' memory

## Available Volumes

${allVolumeNames.map(v => `- ${v}`).join("\n")}
`
  writeFileSync(stellarioAgentPath, stellarioContent)
  console.log(`✓ Guide: stellario.md`)
}

// ── 7. npm install ─────────────────────────────────────────────────────────

if (needsInstall) {
  console.log("")
  console.log("Installing dependencies in .opencode/...")
  try {
    execSync("npm install", { cwd: opencodeDir, stdio: "pipe" })
    console.log("✓ npm install")
  } catch {
    console.log(`⚠  npm install failed. Run manually: cd .opencode && npm install`)
  }
}

// ── 8. .gitignore ──────────────────────────────────────────────────────────

const gitignorePath = join(projectRoot, ".gitignore")
if (existsSync(gitignorePath)) {
  const gitignore = readFileSync(gitignorePath, "utf-8")
  if (!gitignore.includes(".opencode/")) {
    writeFileSync(gitignorePath, gitignore.trimEnd() + "\n.opencode/\n")
    console.log(`✓ .gitignore: added .opencode/`)
  }
} else {
  writeFileSync(gitignorePath, ".opencode/\n")
  console.log(`✓ .gitignore: created`)
}

console.log("")
console.log("Done! Next steps:")
console.log(`  1. Edit .opencode/stellario.yaml to customize`)
console.log(`  2. Create type:prompt entries in meta volume for dynamic prompts`)
console.log(`  3. Start opencode — tools, plugin, and prompts auto-discovered`)

// ── Helpers ────────────────────────────────────────────────────────────────

function getArg(args, flag) {
  const idx = args.indexOf(flag)
  if (idx === -1 || idx + 1 >= args.length) return undefined
  return args[idx + 1]
}

function getStellarioVersion() {
  try {
    const pkgPath = resolve(join(__dirname, "..", "..", "package.json"))
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
    return pkg.version || "latest"
  } catch {
    return "latest"
  }
}

