#!/usr/bin/env node
// Stellario CLI — pure JS, no build step needed
// This file is the npm bin entry point

import { existsSync, mkdirSync, writeFileSync, cpSync, readFileSync } from "fs"
import { join, resolve, dirname } from "path"
import { execSync } from "child_process"
import { fileURLToPath } from "url"
import { parse as parseYaml } from "yaml"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const TEMPLATES = ["minimal", "novel", "software", "audit"]
const STELLARIO_REPO = "github:FadingRose/stellario"

// Glue files are shipped in glue/ directory — no inline templates needed.
// Mapping: glue source filename → target filename in .opencode/tools/
const GLUE_FILES = {
  "memory.ts": "stellario-memory.ts",
  "telescope.ts": "stellario-telescope.ts",
  "workspace.ts": "stellario-workspace.ts",
  "volume-link.ts": "stellario-volume-link.ts",
}

// ── Main ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2)
const command = args[0]

if (!command || command === "help" || command === "--help") {
  console.log(`stellario — agent memory infrastructure

Usage:
  stellario init [--template <name>] [--root <path>]

Commands:
  init    Initialize Stellario in a project

Options:
  -t, --template <name>   Config template: ${TEMPLATES.join(", ")} (default: minimal)
      --root <path>       Project root directory (default: current directory)

Examples:
  npx github:FadingRose/stellario init --template software
  npx stellario init --template novel --root /path/to/project
`)
  process.exit(0)
}

if (command !== "init") {
  console.error(`Unknown command: ${command}`)
  process.exit(1)
}

// ── Init ──────────────────────────────────────────────────────────────────

const template = getArg(args, "--template") || getArg(args, "-t") || "minimal"
const projectRoot = resolve(getArg(args, "--root") || ".")

if (!TEMPLATES.includes(template)) {
  console.error(`Unknown template: "${template}". Available: ${TEMPLATES.join(", ")}`)
  process.exit(1)
}

if (!existsSync(projectRoot)) {
  console.error(`Directory not found: ${projectRoot}`)
  process.exit(1)
}

console.log(`Stellario init — template: ${template}`)
console.log(`Project root: ${projectRoot}`)
console.log("")

const opencodeDir = join(projectRoot, ".opencode")
const configPath = join(opencodeDir, "stellario.yaml")

// ── 1. Config ──────────────────────────────────────────────────────────────

const packageRoot = resolve(join(__dirname, "..", ".."))

if (existsSync(configPath)) {
  console.log(`⚠  Config already exists: ${configPath} (skipped)`)
} else {
  const templatePath = join(packageRoot, "templates", `${template}.yaml`)

  if (!existsSync(templatePath)) {
    console.error(`Template not found: ${templatePath}`)
    console.error(`Available templates: ${TEMPLATES.join(", ")}`)
    process.exit(1)
  }

  mkdirSync(opencodeDir, { recursive: true })
  cpSync(templatePath, configPath)
  console.log(`✓ Config: ${configPath}`)
}

// ── 2. Load config ─────────────────────────────────────────────────────────

const config = parseYaml(readFileSync(configPath, "utf-8"))
const agents = Object.keys(config.agents || {})
const volumes = config.volumes || {}

// ── 3. Memory directory + git init ─────────────────────────────────────────

const memDir = join(projectRoot, config.memoryDir || ".opencode/.stellario")
if (!existsSync(memDir)) {
  mkdirSync(memDir, { recursive: true })
  console.log(`✓ Memory dir: ${memDir}`)
}

if (!existsSync(join(memDir, ".git"))) {
  try {
    execSync("git init", { cwd: memDir, stdio: "pipe" })
    console.log(`✓ Memory git init`)
  } catch {
    console.log(`⚠  git init failed in ${memDir}`)
  }
} else {
  console.log(`  Memory git: already initialized`)
}

// .gitignore inside memDir (exclude generated index files)
const memGitignore = join(memDir, ".gitignore")
if (!existsSync(memGitignore)) {
  writeFileSync(memGitignore, "# Generated by Stellario — do not edit\nkeywords-index.jsonl\n")
  console.log(`✓ Memory .gitignore: created`)
} else {
  const gi = readFileSync(memGitignore, "utf-8")
  if (!gi.includes("keywords-index.jsonl")) {
    writeFileSync(memGitignore, gi.trimEnd() + "\nkeywords-index.jsonl\n")
    console.log(`✓ Memory .gitignore: added keywords-index.jsonl`)
  }
}

// ── 4. package.json ────────────────────────────────────────────────────────

const pkgPath = join(opencodeDir, "package.json")
let needsInstall = false

if (!existsSync(pkgPath)) {
  const version = getStellarioVersion()
  const stellarioDep = version === "latest" ? STELLARIO_REPO : `${STELLARIO_REPO}#v${version}`
  const pkg = {
    private: true,
    dependencies: {
      "@opencode-ai/plugin": "latest",
      zod: "^3.23.0",
      stellario: stellarioDep,
    },
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n")
  needsInstall = true
  console.log(`✓ package.json: created`)
} else {
  const existingPkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
  const deps = existingPkg.dependencies || {}
  if (!deps.stellario) {
    const version = getStellarioVersion()
    deps.stellario = version === "latest" ? STELLARIO_REPO : `${STELLARIO_REPO}#v${version}`
    existingPkg.dependencies = deps
    writeFileSync(pkgPath, JSON.stringify(existingPkg, null, 2) + "\n")
    needsInstall = true
    console.log(`✓ package.json: added stellario dependency`)
  } else {
    console.log(`  package.json: stellario already listed`)
  }
}

// ── 5. Glue files (copied from shipped glue/ directory) ──────────────────────

const toolsDir = join(opencodeDir, "tools")
mkdirSync(toolsDir, { recursive: true })

const glueDir = join(packageRoot, "glue")
for (const [src, dest] of Object.entries(GLUE_FILES)) {
  const srcPath = join(glueDir, src)
  const destPath = join(toolsDir, dest)
  if (existsSync(destPath)) {
    console.log(`  Tools: ${dest} (exists, skipped)`)
  } else {
    cpSync(srcPath, destPath)
    console.log(`✓ Tools: ${dest}`)
  }
}

// ── 5b. Plugin injector ─────────────────────────────────────────────────────

const pluginDir = join(opencodeDir, "plugin")
mkdirSync(pluginDir, { recursive: true })
const pluginSrc = join(glueDir, "plugin.ts")
const pluginDest = join(pluginDir, "stellario-inject.ts")
if (existsSync(pluginDest)) {
  console.log(`  Plugin: stellario-inject.ts (exists, skipped)`)
} else {
  cpSync(pluginSrc, pluginDest)
  console.log(`✓ Plugin: stellario-inject.ts`)
}

// ── 6. Agent skeletons ─────────────────────────────────────────────────────

const agentsDir = join(opencodeDir, "agents")
mkdirSync(agentsDir, { recursive: true })

const memoryTools = ["stellario-memory_create", "stellario-memory_show", "stellario-memory_revise", "stellario-memory_forget", "stellario-memory_history", "stellario-memory_meta", "stellario-memory_ref", "stellario-memory_unref"]
const searchTools = ["stellario-telescope_search"]
const workspaceTools = ["stellario-workspace_status", "stellario-workspace_assemble", "stellario-workspace_open", "stellario-workspace_edit", "stellario-workspace_add", "stellario-workspace_remove"]
const volumeLinkTools = ["stellario-volume-link_discover", "stellario-volume-link_link", "stellario-volume-link_unlink"]

for (const agent of agents) {
  const agentPath = join(agentsDir, `${agent}.md`)
  if (existsSync(agentPath)) {
    console.log(`  Agent: ${agent}.md (exists, skipped)`)
    continue
  }

  const agentDef = config.agents[agent] || {}
  const isPrimary = agentDef.role === "primary"
  const display = agentDef.display || agent

  const canWriteAny = Object.entries(volumes)
    .some(([, def]) => (def.boundaries?.write || []).includes(agent))

  const accessibleVolumes = Object.entries(volumes)
    .filter(([, def]) => {
      const write = def.boundaries?.write || []
      const read = def.boundaries?.read || []
      return write.includes(agent) || read.includes(agent) || read.includes("all")
    })
    .map(([name]) => name)

  // Build tools list based on role and permissions
  const agentTools = []

  // Primary agent gets task delegation + code editing
  if (isPrimary) {
    agentTools.push("  task: true")
    agentTools.push("  edit: true")
    agentTools.push("  bash: true")
  }

  // Memory tools based on write permissions
  if (canWriteAny) {
    agentTools.push(...memoryTools.map(t => `  ${t}: true`))
  } else {
    agentTools.push("  memory_show: true", "  memory_history: true")
  }
  agentTools.push(...searchTools.map(t => `  ${t}: true`))
  agentTools.push(...workspaceTools.map(t => `  ${t}: true`))
  agentTools.push(...volumeLinkTools.map(t => `  ${t}: true`))

  const toolsYaml = agentTools.join("\n")

  const agentBody = isPrimary
    ? `# ${display}

You are a memory-aware agent powered by Stellario. You manage structured, version-controlled memory across sessions.

## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \`status\` to bootstrap.

## When Memory Is Empty

If you see "Memory: empty" in the injected status, this is a fresh install. Enter **wizard mode** and walk the user through these steps:

### Step 1: Greet & Learn

Greet the user. Ask what they're working on and what kind of memory they need. Fill in the introduction section below.

### Step 2: First Entry

Create the user's first memory entry. This demonstrates the core flow:

\`\`\`
memory_create(
  content="## Project: {name}\\n{description}",
  tags=["type:convention"],
  keywords=["{project}", "overview"]
)
\`\`\`

Explain: entries live in volumes, each has a profile (mutable/append/scratch/frozen/workspace), and entries are git-tracked.

### Step 3: Second Entry + Ref

Create a second related entry, then link them:

\`\`\`
memory_create(content="## {topic}", tags=["type:design"], keywords=["{topic}"])
memory_ref(id="{first_id}", target="{second_id}", reason="design context for this project")
\`\`\`

Explain: refs form a knowledge graph. \`ref\` is manual, \`unref\` removes a ref. Auto-refs engine can also link entries automatically based on tag/keyword overlap.

### Step 4: Search

Demonstrate search:

\`\`\`
search(query="{keyword}")
search(tags=["type:design"])
search(returns="tags")
\`\`\`

Explain: hybrid search combines text matching with semantic embedding. Tags filter precisely, keywords enable concept-level discovery.

### Step 5: Workspace

Create a workspace theme to gather related entries:

\`\`\`
workspace_assemble(
  content="## Current Focus\\nWorking on {topic}",
  entries=["{id1}", "{id2}"]
)
\`\`\`

Then open it: \`workspace_open()\`. This shows all gathered entries inline.

Explain: workspace tracks your active context across sessions. Only one workspace volume per project.

### Step 6: Volume Link (Optional)

If the user has other stellario projects, show them cross-project memory:

\`\`\`
discover(path="/path/to/other/project")
link(project="/path/to/other/project", volume="active", alias="other_active")
\`\`\`

Linked volumes are readonly — you observe without modifying.

### Step 7: Meta Calibration

Create a behavioral calibration that persists across sessions:

\`\`\`
meta(content="Always confirm before archiving entries")
\`\`\`

Meta entries with tag \`type:prompt\` are auto-injected into your system context on every session start.

## User Introduction

Fill this in during the first conversation. Update whenever the user's needs change.

<!-- INTRODUCTION_START -->
## About the User

*(Not yet filled in — ask during onboarding)*
<!-- INTRODUCTION_END -->

## Memory Philosophy

- Write to memory when you learn something worth remembering across sessions
- Use \`meta\` for behavioral calibrations (injected as prompts)
- Use append volumes for handoff logs (immutable records)
- Use scratch volumes for temporary drafts (not git-tracked)
- Use \`workspace_assemble\` to gather related entries into a focused context
- Use \`ref\` / \`unref\` for manual knowledge graph edges
- Use \`discover\` / \`link\` to observe other projects' memory

## Available Volumes

${accessibleVolumes.map(v => `- ${v}`).join("\n")}
`
    : `# ${display}

Volumes: ${accessibleVolumes.join(", ")}
`

  const content = `---
description: ${display}
mode: primary
tools:
${toolsYaml}
---

${agentBody}
`
  writeFileSync(agentPath, content)
  console.log(`✓ Agent: ${agent}.md (${isPrimary ? "primary" : "subagent"})`)
}

// ── 6b. Stellario guide (always present, regardless of template) ──────────

if (agents.includes("stellario")) {
  console.log(`  Guide: stellario.md (already generated from template)`)
} else {
const stellarioAgentPath = join(agentsDir, "stellario.md")
if (existsSync(stellarioAgentPath)) {
  console.log(`  Guide: stellario.md (exists, skipped)`)
} else {
  const allVolumeNames = Object.keys(volumes)
  const stellarioTools = [
    ...memoryTools,
    ...searchTools,
    ...workspaceTools,
    ...volumeLinkTools,
  ].map(t => `  ${t}: true`).join("\n")

  const stellarioContent = `---
description: Stellario
mode: primary
tools:
${stellarioTools}
---

# Stellario

You are the memory guide. Your job is to help the user understand and use the Stellario memory system.

## Startup

Your operational context is auto-injected via plugin on session start. The injected status shows volume stats, active workspace, latest handover, linked volumes, and dynamic prompts from the meta volume.

If the plugin is not active, call \`status\` to bootstrap.

## When Memory Is Empty

If you see "Memory: empty" in the injected status, this is a fresh install. Enter **wizard mode** and walk the user through these steps:

### Step 1: Greet & Learn

Greet the user. Ask what they're working on and what kind of memory they need. Fill in the introduction section below.

### Step 2: First Entry

Create the user's first memory entry:

\`\`\`
memory_create(
  content="## Project: {name}\\\\n{description}",
  tags=["type:convention"],
  keywords=["{project}", "overview"]
)
\`\`\`

Explain: entries live in volumes, each has a profile (mutable/append/scratch/frozen/workspace), and entries are git-tracked.

### Step 3: Second Entry + Ref

Create a second related entry, then link them:

\`\`\`
memory_create(content="## {topic}", tags=["type:design"], keywords=["{topic}"])
memory_ref(id="{first_id}", target="{second_id}", reason="design context for this project")
\`\`\`

Explain: refs form a knowledge graph. \`ref\` is manual, \`unref\` removes a ref. Auto-refs engine can also link entries automatically based on tag/keyword overlap.

### Step 4: Search

Demonstrate search:

\`\`\`
search(query="{keyword}")
search(tags=["type:design"])
search(returns="tags")
\`\`\`

Explain: hybrid search combines text matching with semantic embedding. Tags filter precisely, keywords enable concept-level discovery.

### Step 5: Workspace

Create a workspace theme to gather related entries:

\`\`\`
workspace_assemble(
  content="## Current Focus\\\\nWorking on {topic}",
  entries=["{id1}", "{id2}"]
)
\`\`\`

Then open it: \`workspace_open()\`. This shows all gathered entries inline.

Explain: workspace tracks your active context across sessions. Only one workspace volume per project.

### Step 6: Volume Link (Optional)

If the user has other stellario projects, show them cross-project memory:

\`\`\`
discover(path="/path/to/other/project")
link(project="/path/to/other/project", volume="active", alias="other_active")
\`\`\`

Linked volumes are readonly — you observe without modifying.

### Step 7: Meta Calibration

Create a behavioral calibration that persists across sessions:

\`\`\`
meta(content="Always confirm before archiving entries")
\`\`\`

Meta entries with tag \`type:prompt\` are auto-injected into your system context on every session start.

## User Introduction

Fill this in during the first conversation. Update whenever the user's needs change.

<!-- INTRODUCTION_START -->
## About the User

*(Not yet filled in — ask during onboarding)*
<!-- INTRODUCTION_END -->

## Memory Philosophy

- Write to memory when you learn something worth remembering across sessions
- Use \`meta\` for behavioral calibrations (injected as prompts)
- Use append volumes for handoff logs (immutable records)
- Use scratch volumes for temporary drafts (not git-tracked)
- Use \`workspace_assemble\` to gather related entries into a focused context
- Use \`ref\` / \`unref\` for manual knowledge graph edges
- Use \`discover\` / \`link\` to observe other projects' memory

## Available Volumes

${allVolumeNames.map(v => `- ${v}`).join("\n")}
`
  writeFileSync(stellarioAgentPath, stellarioContent)
  console.log(`✓ Guide: stellario.md (wizard)`)
  }
} // end else

// ── 7. npm install ─────────────────────────────────────────────────────────

if (needsInstall) {
  console.log("")
  console.log("Installing dependencies in .opencode/...")
  try {
    execSync("npm install", { cwd: opencodeDir, stdio: "pipe" })
    console.log("✓ npm install")
  } catch {
    console.log(`⚠  npm install failed. Run manually: cd .opencode && npm install`)
  }
}

// ── 8. .gitignore ──────────────────────────────────────────────────────────

const gitignorePath = join(projectRoot, ".gitignore")
if (existsSync(gitignorePath)) {
  const gitignore = readFileSync(gitignorePath, "utf-8")
  if (!gitignore.includes(".opencode/")) {
    writeFileSync(gitignorePath, gitignore.trimEnd() + "\n.opencode/\n")
    console.log(`✓ .gitignore: added .opencode/`)
  }
} else {
  writeFileSync(gitignorePath, ".opencode/\n")
  console.log(`✓ .gitignore: created`)
}

console.log("")
console.log("Done! Next steps:")
console.log(`  1. Edit .opencode/stellario.yaml to customize`)
console.log(`  2. Create type:prompt entries in meta volume for dynamic prompts`)
console.log(`  3. Start opencode — tools, plugin, and prompts auto-discovered`)

// ── Helpers ────────────────────────────────────────────────────────────────

function getArg(args, flag) {
  const idx = args.indexOf(flag)
  if (idx === -1 || idx + 1 >= args.length) return undefined
  return args[idx + 1]
}

function getStellarioVersion() {
  try {
    const pkgPath = resolve(join(__dirname, "..", "..", "package.json"))
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
    return pkg.version || "latest"
  } catch {
    return "latest"
  }
}

