// Public API — pure definitions, no runtime coupling
export { getMemoryToolDefs } from "./defs/memory-defs.js"
export { getWorkspaceToolDefs, buildStatus } from "./defs/workspace-defs.js"
export { getTelescopeToolDefs } from "./defs/telescope-defs.js"
export { getCoordinationToolDefs } from "./defs/coordination-defs.js"
export { getLspToolDefs } from "./defs/lsp-defs.js"
export { getAstGrepToolDefs } from "./defs/ast-grep-defs.js"
export { getVolumeLinkDefs } from "./defs/volume-link-defs.js"
export { readLinkedVolume } from "./defs/volume-link-defs.js"
export * as embedding from "./embedding.js"
export { computeAutoRefs, applyAutoRefsPlan, hasTagOverlap, isRefsRemovedBlocked, hasAutoLink, formatAutoReason } from "./auto-refs.js"
export type { AutoRefsPlan, AutoRefPair, AutoRefRemove } from "./auto-refs.js"
export type { AutoRefsConfig, LinkedVolume } from "./types.js"
export { triggerInit as triggerLspInit, getLspStatus, shutdownAll as shutdownAllLsp } from "./lsp/manager.js"
export { recoverOnLoad, markPending, unmarkPending, hasPending, flushIndexWorker, triggerFlush } from "./index-worker.js"
